# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 61285c8a5dbf56eb52bfdb9a4976d66abc732ac98abde891c0b6f5f9f62dc736e2f31ce4b07646c6b884a188bbf91e715e623da4c230c8c50c11bb4c20b15c50

test:
  secret_key_base: 9f88e26b263aa95610101af8d074cd66eb31d805c6f4336fcea59b650ecb0bc4a7be23e05a5abb866495a1d88e3e35e062002b81e523bc3e503ac4a593d0263b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
